name: Version Check

on:
  pull_request:
    branches:
      - main

jobs:
  check_version:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 2

      - name: Check if VERSION file changed
        run: |
          if git diff --name-only HEAD^ HEAD | grep -q "VERSION"; then
            echo "VERSION file has been updated."
          else
            echo "Error: VERSION file has not been updated in this push."
            exit 1
          fi
